In [1]:
import logging
logging.basicConfig(level=logging.INFO)

import time
import awa_interface
from observations.yag_screen import YAGScreen
from xopt.bayesian.algorithms import bayesian_exploration

from botorch.acquisition.analytic import UpperConfidenceBound

def acq

class Evaluator:
    def __init__(self, interface):
        self.interface = interface

    def evaluate_emittance(self, inputs):
        self.interface.set_parameters(inputs)

        time.sleep(1.0)

        observation = YAGScreen(self.interface,
                                n_samples=5,
                                average_measurements=True)

        results = observation.measure_screen()
        logging.debug('done analyzing images')
        
        #remove a bunch of excess info
        pop_args = ['ellipses', 'processed_images', 'raw_images']
        for ele in pop_args:
            results.pop(ele)
        return results


VOCS = {
    'name': 'AWA_Exp',

    'variables': {
        'Drive:Ctrl:DS1': [6.05, 9.07],  # Focusing Solenoid
        'Drive:Ctrl:DS3': [0.0, 2.5],  # Matching Solenoid
        #'SMCtrl:AWA:abs03': [-640, 640],  # Linac Phase
        'AWA:Bira3Ctrl:Ch03': [-0.5, 0.5],  # DQ4
        'AWA:Bira3Ctrl:Ch04': [-0.5, 0.5],  # DQ5
        'AWA:Bira3Ctrl:Ch05': [-0.5, 0.5],  # DQ6

    },

    'objectives': {
        'rms_x': None,
    },

    'constraints': {
        'rms_x': ['LESS_THAN', 150],
        'rms_y': ['LESS_THAN', 150],
        'centroid_offset': ['LESS_THAN', 500],
        'n_blobs': ['GREATER_THAN', 3]

    },
    'constants': {}

}

awa_interface = awa_interface.AWAInterface(use_frame_grabber=False, testing=False)
evaluator = Evaluator(awa_interface)
opt_results = bayesian_exploration(VOCS,
                                   evaluator.evaluate_emittance,
                                   n_initial_samples=10,
                                   n_steps=100)


INFO:awa_interface:Starting controller_interface
INFO:awa_interface:Connecting to AWAPGCamera application
INFO:awa_interface:Done
INFO:xopt.bayesian.optimize:started running optimization with generator: <xopt.bayesian.generators.exploration.BayesianExplorationGenerator object at 0x0000018EC5CC6790>
INFO:xopt.bayesian.optimize:submitting initial candidates at time 2021-09-21T16:21:51-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:awa_interface:taking n samples 5
  File "e:\awasoftware\xopt\xopt\xopt\xopt\bayesian\utils.py", line 203, in sampler_evaluate
    outputs = evaluate_f(inputs, *eval_args)
  File "C:\Users\aw

{'Exception': "Weights sum to zero, can't be normalized", 'Traceback': None}


INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:awa_interface:taking n samples 5
INFO:xopt.bayesian.optimize:starting optimization loop
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:22:43-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:22:51-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xo

E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:23:49-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:23:56-05:00
INFO:awa_interface:taking n samples 5
E:\AWA

INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:25:04-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:25:12-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:x

INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:26:36-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:26:43-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:x

INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:28:22-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:28:31-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:x

E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:30:01-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:30:11-05:00
INFO:awa_interface:taking n samples 5
E:\AWA

E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:31:59-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:32:09-05:00
INFO:awa_interface:taking n samples 5
E:\AWA

INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:33:53-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:34:05-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:x

E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:35:59-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:36:11-05:00
INFO:awa_interface:taking n samples 5
E:\AWA

INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:37:46-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:xopt.bayesian.optimize:submitting candidates at time 2021-09-21T16:37:57-05:00
INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])
INFO:x

In [2]:
print(opt_results)

{'variables': tensor([[ 7.2562e+00,  1.1869e+00, -6.8835e-02,  4.6426e-01,  1.2625e-01],
        [ 8.3915e+00,  1.8550e+00, -1.2788e-01, -2.5338e-01,  3.8095e-01],
        [ 8.3597e+00,  1.2112e+00, -1.8348e-01,  4.6214e-01, -2.0116e-01],
        [ 6.3012e+00,  8.8784e-01, -4.4555e-01,  2.6385e-01, -1.2295e-01],
        [ 8.4625e+00,  2.0069e+00, -4.5636e-01, -3.8974e-01,  2.1764e-01],
        [ 6.7775e+00,  2.3475e+00,  9.1057e-02, -1.0531e-01,  4.1330e-01],
        [ 7.2637e+00,  1.6861e+00,  4.9561e-01, -8.1719e-02,  3.8719e-01],
        [ 7.1786e+00,  7.8265e-01,  8.9846e-02, -2.3489e-01, -1.4638e-01],
        [ 7.3579e+00,  2.3721e+00,  4.3442e-01,  2.7582e-01, -2.3093e-01],
        [ 6.5155e+00,  1.6993e+00, -1.4000e-01,  3.0420e-01,  4.1821e-01],
        [ 6.0500e+00,  2.2687e+00, -1.3915e-02,  1.7360e-01,  2.1591e-01],
        [ 7.4098e+00,  1.9786e+00, -2.0396e-01,  2.1069e-01,  5.0000e-01],
        [ 6.3150e+00,  1.8782e+00, -4.2085e-01,  1.5172e-01,  5.0000e-01],
        [ 6

In [3]:
X = opt_results['variables'][-8]
X_in = dict(zip(VOCS['variables'], X))
res = evaluator.evaluate_emittance(X_in)
print(res['rms_x'])
print(res['rms_y'])
print(res['centroid_offset'])
print(res['n_blobs'])

INFO:awa_interface:taking n samples 5
E:\AWASoftware\xopt\xopt\awa_control\observations\yag_screen.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  outputs[ele] = np.array(outputs[ele])


36.41076430380727
83.69350908624344
394.6504562657636
5.4


In [4]:
print(res.keys())
print(res['charge'])

dict_keys(['rms_x', 'rms_y', 'n_blobs', 'image_check', 'centroid_offset', 'FWHMX', 'FWHMY', 'FWHML', 'CX', 'CY', 'charge', 'ROI'])
[[-1.20645057e-08  2.87351131e-11  0.00000000e+00  0.00000000e+00]
 [-1.20645057e-08  2.87351131e-11  0.00000000e+00  0.00000000e+00]
 [-1.20645057e-08  2.87351131e-11  0.00000000e+00  0.00000000e+00]
 [-1.20645057e-08  2.87351131e-11  0.00000000e+00  0.00000000e+00]
 [-1.20645057e-08  2.87351131e-11  0.00000000e+00  0.00000000e+00]]
